version: "3.8"

services:


    image: redis
    hostname: redis
    container_name: redis
    restart: always

    ports:
      - '${REDIS_PORT}:6379'
    command:
      - '/bin/sh'
      - '-c'


  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:

