# Generated by Django 3.2.13 on 2022-06-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_data_migration_remove_tmp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessons",
            options={"ordering": ("course", "num"), "verbose_name": "Lesson", "verbose_name_plural": "Lessons"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ("-created",), "verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="teachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
    ]
