# Generated by Django 3.2.13 on 2022-06-05 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_coursefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefeedback",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="coursefeedback",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
