# Generated by Django 3.2.13 on 2022-06-04 20:44

from django.db import migrations

import authapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", authapp.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
